server:
  port: 18888
spring:
  application:
    name: light-boot
  datasource:
    url: jdbc:mysql://localhost:3306/practice?rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    host: prepare.mssh.landdt.cn
    port: 6379
    database: 12
    password: 5gBdm!D4
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1500  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

